import React,{useEffect,useMemo,useState} from "react";

type Message={role:"user"|"ai";text:string;confidence?:number};
type Stats={knowledgeEntries:number;memoryEntries:number;vocabSize:number;parameters:number;epochs:number;steps:number;loss:number;learningRate:number;training:any};

const pages=["Chat","Training","Knowledge","Memory","Model"] as const;

async function api(path:string, options:RequestInit={}){const r=await fetch(path,{...options,headers:{"Content-Type":"application/json",...(options.headers||{})}});const j=await r.json();if(!r.ok)throw new Error(j.error||"Request failed");return j}

export default function App(){
 const [page,setPage]=useState<typeof pages[number]>("Chat"),[open,setOpen]=useState(false);
 const [messages,setMessages]=useState<Message[]>([{role:"ai",text:"Hey! I'm NeuroAI. I'm running on your Node.js brain. Ask me something, teach me, or watch the model train."}]);
 const [input,setInput]=useState(""),[busy,setBusy]=useState(false),[stats,setStats]=useState<Stats|null>(null),[query,setQuery]=useState(""),[knowledge,setKnowledge]=useState<any[]>([]);
 const refresh=()=>api("/api/stats").then(setStats).catch(()=>{});
 useEffect(()=>{refresh();const id=setInterval(refresh,1500);return()=>clearInterval(id)},[]);
 const send=async(text=input)=>{text=text.trim();if(!text||busy)return;setInput("");setMessages(m=>[...m,{role:"user",text},{role:"ai",text:"Thinking…"}]);setBusy(true);try{const j=await api("/api/chat",{method:"POST",body:JSON.stringify({message:text})});setMessages(m=>{const x=[...m];x[x.length-1]={role:"ai",text:j.text,confidence:j.confidence};return x})}catch(e:any){setMessages(m=>{const x=[...m];x[x.length-1]={role:"ai",text:"Backend error: "+e.message};return x})}finally{setBusy(false)}};
 const search=async()=>{const q=query?`?q=${encodeURIComponent(query)}`:"";setKnowledge(await api("/api/knowledge"+q))};
 const train=async(action:"start"|"stop")=>{await api(`/api/training/${action}`,{method:"POST"});refresh()};
 const nav=(p:any)=>{setPage(p);setOpen(false);if(p==="Knowledge")search()};
 return <div className="shell">
  <aside className={open?"side open":"side"}><div className="brand"><div className="logo">∿</div><div><b>Neuro<span>AI</span></b><small>Node Neural Lab</small></div></div><nav>{pages.map(p=><button className={page===p?"nav active":"nav"} onClick={()=>nav(p)} key={p}>{p==="Chat"?"◉":p==="Training"?"⚡":p==="Knowledge"?"◈":p==="Memory"?"⌁":"◇"}<span>{p}</span></button>)}</nav><div className="sideFoot"><i/> {stats?.training?.status==="running"?"Training":"Node online"}</div></aside>
  <main><header><button className="menu" onClick={()=>setOpen(!open)}>☰</button><div><strong>{page}</strong><small>{page==="Chat"?"Talk to your local model":page==="Training"?"Live parameter learning":page==="Knowledge"?"Q&A database":page==="Memory"?"Persistent memory":"Architecture & parameters"}</small></div><div className="pill"><i/> NODE</div></header>
  {page==="Chat"&&<section className="content chat"><div className="messages">{messages.map((m,i)=><div className={"msg "+m.role} key={i}><div className="avatar">{m.role==="ai"?"N":"🙂"}</div><div className="bubble"><b>{m.role==="ai"?"NeuroAI":"You"}</b><p>{m.text}</p>{m.confidence!=null&&<small>match confidence {(m.confidence*100).toFixed(0)}%</small>}</div></div>)}</div><div className="quick">{["What is artificial intelligence?","How does training work?","Teach me something"].map(x=><button key={x} onClick={()=>send(x)}>{x}</button>)}</div><div className="composer"><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Message NeuroAI…"/><button onClick={()=>send()} disabled={busy}>↑</button></div></section>}
  {page==="Training"&&<section className="content"><div className="hero"><div><label>NEURAL TRAINING</label><h1>Train the brain.</h1><p>Native Node.js training with real gradient updates, saved weights and automatic epochs.</p></div><div className="actions"><button className="primary" onClick={()=>train("start")}>▶ Start</button><button onClick={()=>train("stop")}>■ Stop</button></div></div><div className="cards">{[["EPOCHS",stats?.epochs??0],["STEPS",stats?.steps??0],["LOSS",stats?.loss?.toFixed?.(4)??"—"],["LEARNING RATE",stats?.learningRate?.toFixed?.(5)??"—"]].map(x=><div className="card" key={x[0]}><small>{x[0]}</small><b>{x[1]}</b></div>)}</div><div className="panel"><div className="panelTitle"><b>Training monitor</b><span className="badge">{(stats?.training?.status||"idle").toUpperCase()}</span></div><div className="bars">{Array.from({length:32},(_,i)=><i key={i} style={{height:`${20+((i*37)%70)}%`}}/>)}</div></div></section>}
  {page==="Knowledge"&&<section className="content"><div className="hero"><div><label>DATABASE</label><h1>Knowledge.</h1><p>{stats?.knowledgeEntries?.toLocaleString()??"—"} stored training records.</p></div></div><div className="search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search questions…"/><button onClick={search}>Search</button></div><div className="list">{knowledge.slice(0,30).map((e:any)=><article key={e.id}><b>{e.question}</b><p>{e.answer}</p><small>{e.category||"General"}</small></article>)}</div></section>}
  {page==="Memory"&&<section className="content"><div className="hero"><div><label>LONG-TERM MEMORY</label><h1>Memory.</h1><p>Local conversation memory stored by the Node process.</p></div></div><div className="cards"><div className="card"><small>MEMORIES</small><b>{stats?.memoryEntries??0}</b></div><div className="card"><small>VOCABULARY</small><b>{stats?.vocabSize??0}</b></div></div><div className="panel"><b>Memory is local.</b><p>Teach NeuroAI through the API and the data is saved under <code>data/</code>.</p></div></section>}
  {page==="Model"&&<section className="content"><div className="hero"><div><label>ARCHITECTURE</label><h1>Inside the brain.</h1><p>React TSX interface + TypeScript Node backend + native HTTP server.</p></div></div><div className="architecture">{["TOKEN IDs → 4096 vocabulary","EMBEDDINGS → 64 dimensions","CONTEXT POOL → 12 tokens","HIDDEN → 128 neurons + tanh","SOFTMAX → next-token probabilities","BACKPROP → trainable parameters"].map(x=><div key={x}>{x}</div>)}</div><div className="cards"><div className="card"><small>PARAMETERS</small><b>{(stats?.parameters??0).toLocaleString()}</b></div><div className="card"><small>VOCAB</small><b>{stats?.vocabSize??0}</b></div></div></section>}
  </main></div>
}
